#!/usr/bin/env python3
"""Generate cubiomes' tables/plist262.h from the game's own biome parameter report.

    java -DbundlerMainClass=net.minecraft.data.Main -jar server/cache/mojang_26.2.jar \\
         --reports --output reports
    python3 gen_plist262.py reports/reports/biome_parameters/minecraft/overworld.json \\
         path/to/cubiomes/biomes.h > path/to/cubiomes/tables/plist262.h

The report is the multi-noise parameter list the server uses to pick overworld biomes:
one row per climate box, in the order the game holds them. Values are quantised the way
Climate.quantizeCoord does it, (long)(float * 10000.0F), so the table carries exactly the
integers the game compares against. Biome names are mapped to cubiomes' enum, resolving
the aliases it keeps for renamed biomes (snowy_plains is snowy_tundra, and so on).
"""

import json
import re
import struct
import sys


def quantise(value: float) -> int:
    f = struct.unpack("f", struct.pack("f", float(value)))[0]
    return int(struct.unpack("f", struct.pack("f", f * 10000.0))[0])


def enum_ids(biomes_h: str) -> dict:
    """Name -> id from cubiomes' enum, aliases included."""
    text = open(biomes_h, encoding="utf-8").read()
    body = text[text.index("enum BiomeID"):]
    body = body[:body.index("};")]
    ids: dict = {}
    value = -1
    for line in body.splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line or line.startswith("enum") or line.startswith("{"):
            continue
        for item in line.split(","):
            item = item.strip()
            if not item:
                continue
            if "=" in item:
                name, rhs = (s.strip() for s in item.split("=", 1))
                plus = re.fullmatch(r"([a-z_][a-z_0-9]*)\s*\+\s*(\d+)", rhs)
                if re.fullmatch(r"-?\d+", rhs):
                    value = int(rhs)
                elif rhs in ids:
                    ids[name] = ids[rhs]
                    continue
                elif plus and plus.group(1) in ids:
                    ids[name] = ids[plus.group(1)] + int(plus.group(2))
                    continue
                else:
                    raise SystemExit(f"cannot resolve {item!r}")
            else:
                name = item
                value += 1
            ids[name] = value
    return ids


ORDER = ("temperature", "humidity", "continentalness", "erosion", "depth", "weirdness")


def main(argv: list) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    entries = json.load(open(argv[0], encoding="utf-8"))["biomes"]
    ids = enum_ids(argv[1])
    rows = []
    for entry in entries:
        name = entry["biome"].replace("minecraft:", "")
        if name not in ids:
            raise SystemExit(f"biome {name} is not in cubiomes' enum; add it first")
        params = entry["parameters"]
        if params.get("offset", 0.0) != 0.0:
            raise SystemExit("a non-zero offset appeared; the metric must include it")
        row = []
        for key in ORDER:
            v = params[key]
            lo, hi = (v, v) if not isinstance(v, list) else v
            row += [quantise(lo), quantise(hi)]
        rows.append((row, ids[name]))
    out = sys.stdout
    out.write("// Generated by gen_plist262.py from the server's biome_parameters report.\n")
    out.write("// Each row: min,max for temperature, humidity, continentalness, erosion, depth,\n")
    out.write("// weirdness, quantised x10000 exactly as the game does. Do not edit by hand.\n")
    out.write("#include <inttypes.h>\n\n")
    out.write(f"enum {{ plist262_len = {len(rows)} }};\n\n")
    out.write("static const int32_t plist262_ranges[plist262_len][12] = {\n")
    for row, _ in rows:
        out.write("    {" + ",".join(str(v) for v in row) + "},\n")
    out.write("};\n\nstatic const uint8_t plist262_biome[plist262_len] = {\n")
    for i in range(0, len(rows), 24):
        out.write("    " + ",".join(str(b) for _, b in rows[i:i + 24]) + ",\n")
    out.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
